---
# defaults file for kibana
kibana_enable: true
kibana_config_backup: true
kibana_manage_yaml: true

kibana_security: true
kibana_tls: false
kibana_tls_cert: /etc/kibana/certs/cert.pem
kibana_tls_key: /etc/kibana/certs/key.pem
kibana_tls_key_passphrase: "{{ lookup('ansible.builtin.password', '/dev/null chars=ascii_letters,digits length=25', seed='kibana_seed') }}"
elasticstack_ca_dir: /opt/es-ca
elasticstack_ca_pass: PleaseChangeMe #this one remains and will be changed in another PR
elasticstack_initial_passwords: /usr/share/elasticsearch/initial_passwords
kibana_cert_expiration_buffer: 30
kibana_cert_validity_period: 1095
kibana_cert_will_expire_soon: false
kibana_sniff_on_start: false
kibana_sniff_on_connection_fault: false

# "global" variables for all roles
elasticstack_release: 8
elasticstack_full_stack: true
elasticstack_variant: elastic
elasticstack_elasticsearch_http_port: 9200
elasticstack_kibana_port: 5601
